TEE ../LOG/LOG_DROP.TXT
DROP TABLE IF EXISTS INTPROD;
DROP TABLE IF EXISTS PRODOTTO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS INTERVENTO;
DROP TABLE IF EXISTS TIPIINTERVENTO;
DROP TABLE IF EXISTS OPERAZIONE;
DROP TABLE IF EXISTS AUTO;
DROP TABLE IF EXISTS CLIENTE;
NOTEE