TEE ../LOG/LOG_DDL.TXT
SOURCE ../DDL/00-CLIENTE_DDL.sql
SOURCE ../DDL/01-AUTO_DDL.sql
SOURCE ../DDL/02-OPERAZIONE_DDL.sql
SOURCE ../DDL/03-TIPIINTERVENTO_DDL.sql
SOURCE ../DDL/04-INTERVENTO_DDL.sql
SOURCE ../DDL/05-CATEGORIA_DDL.sql
SOURCE ../DDL/06-PRODOTTO_DDL.sql
SOURCE ../DDL/07-INTPROD_DDL.sql
NOTEE