TEE ../LOG/LOG_DML.TXT
SOURCE ../DML/00-CLIENTE_DML.sql
SOURCE ../DML/01-AUTO_DML.sql
SOURCE ../DML/02-OPERAZIONE_DML.sql
SOURCE ../DML/03-TIPIINTERVENTO_DML.sql
SOURCE ../DML/04-INTERVENTO_DML.sql
SOURCE ../DML/05-CATEGORIA_DML.sql
SOURCE ../DML/06-PRODOTTO_DML.sql
SOURCE ../DML/07-INTPROD_DML.sql
NOTEE