CREATE TABLE AUTO
( 
    TARGA VARCHAR(10) NOT NULL,
    CF CHAR(16) NOT NULL,
    MODELLO VARCHAR(25) NOT NULL,
    MARCA VARCHAR(25) NOT NULL,
    DATAIMM DATE NOT NULL
);

ALTER TABLE AUTO ADD PRIMARY KEY (TARGA);
ALTER TABLE AUTO ADD FOREIGN KEY (CF) REFERENCES CLIENTE (CF);