CREATE TABLE INTERVENTO
( 
    IDI INT NOT NULL,
    IDO INT NOT NULL,
    CODTI VARCHAR(4) NOT NULL
);

ALTER TABLE INTERVENTO ADD PRIMARY KEY (IDI);
ALTER TABLE INTERVENTO ADD FOREIGN KEY (IDO) REFERENCES OPERAZIONE (IDO);
ALTER TABLE INTERVENTO ADD FOREIGN KEY (CODTI) REFERENCES TIPIINTERVENTO (CODTI);