CREATE TABLE INTPROD
(  
    CODP CHAR(4) NOT NULL,
    IDI INT NOT NULL,
    QTA FLOAT NOT NULL
);
    
ALTER TABLE INTPROD ADD PRIMARY KEY (CODP,IDI);
ALTER TABLE INTPROD ADD FOREIGN KEY (CODP) REFERENCES PRODOTTO (CODP);
ALTER TABLE INTPROD ADD FOREIGN KEY (IDI) REFERENCES INTERVENTO (IDI);